apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsix-repo
  namespace: coder-com
  labels:
    app.kubernetes.io/name: vsix-repo
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: vsix-repo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vsix-repo
    spec:
      containers:
      - name: vsix-repo
        image: 463164074552.dkr.ecr.eu-west-1.amazonaws.com/vsix-repo
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: vsix-repo
  namespace: coder-com
  labels:
    app.kubernetes.io/name: vsix-repo
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: vsix-repo
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vsix-repo
  namespace: coder-com
  labels:
    app.kubernetes.io/name: vsix-repo
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.provider: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '15'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
    nginx.ingress.kubernetes.io/service-upstream: 'true'
spec:
  tls:
    - hosts:
        - vsix.pam-eu-datserv-devint.aws.pictet.cloud
      secretName: ingress-tls
  rules:
    - host: vsix.pam-eu-datserv-devint.aws.pictet.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vsix-repo
                port:
                  name: http

